image: amazoncorretto:18.0.1-alpine

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew build -x test --stacktrace
  artifacts:
    paths:
      - 'java2ts-core/build/libs/'
      - 'java2ts-plugin/build/libs/'
