image: amazoncorretto:18.0.1-alpine

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew build -x test --stacktrace
  artifacts:
    paths:
      - 'java2ts-core/build/libs/'
      - 'java2ts-plugin/build/libs/'

test:
  stage: test
  script:
    - ./gradlew test --stacktrace
  artifacts:
    reports:
      junit:
        - 'java2ts-core/build/test-results/test/**/TEST-*.xml'
        - 'java2ts-plugin/build/test-results/test/**/TEST-*.xml'