name: build

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  generic-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Build
        run: ./gradlew build -x test --stacktrace --no-daemon

      - name: Test
        run: ./gradlew test --stacktrace --no-daemon
